add *colors to dwm configs
config broke after dwm update, fixes:
```
root@archlinux:/home/vdloo/.dwm# make
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION="6.1" -DXINERAMA
LDFLAGS  = -s -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft
CC       = cc
CC dwm.c
dwm.c: In function ‘setup’:
dwm.c:1586:43: error: ‘colors’ undeclared (first use in this function)
  scheme[SchemeNorm] = drw_scm_create(drw, colors[SchemeNorm], 3);
                                           ^
dwm.c:1586:43: note: each undeclared identifier is reported only once for each function it appears in
Makefile:18: recipe for target 'dwm.o' failed
make: *** [dwm.o] Error 1
```

see the new config.def.h